const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1100}});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
    await page.goto(process.env.SITE_URL || 'http://localhost:4173');
    await page.locator('.deck-card[aria-pressed="true"]').waitFor();
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.locator('#gallery').evaluate(e=>e.scrollIntoView());
    await page.locator('.deck-card[aria-hidden="false"] img').evaluateAll(es=>Promise.all(es.map(i=>i.decode())));
    await page.screenshot({path:'tests/archive-journal.png'});
    assert.equal(await page.locator('#deck-title').innerText(),'A world of green');
    await page.locator('#deck-next').click();
    assert.equal(await page.locator('#deck-title').innerText(),'After the light fades');
    await page.locator('#deck-prev').click();
    await page.locator('.deck-card[aria-pressed="true"]').focus();
    await page.keyboard.press('End');
    assert.equal(await page.locator('#deck-current').innerText(),'27');
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#deck-current').innerText(),'01');
    await page.locator('#deck-open').click();
    assert.equal(await page.locator('#photo-caption').innerText(),'Nature’s great masterpiece');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#deck-open').evaluate(e=>document.activeElement===e),true);
    await page.locator('#deck-range').fill('3');
    await page.locator('[data-layout="shelf"]').click();
    await page.locator('#gallery').evaluate(e=>e.scrollIntoView());
    await page.screenshot({path:'tests/archive-shelf.png'});
    const stage=await page.locator('#deck-stage').boundingBox();
    await page.mouse.move(stage.x+stage.width*.55,stage.y+stage.height*.5);
    await page.mouse.down();await page.mouse.move(stage.x+stage.width*.55-160,stage.y+stage.height*.5,{steps:12});await page.mouse.up();
    assert.equal(await page.locator('#deck-current').innerText(),'05');
    assert.equal(await page.locator('#photo-dialog').evaluate(e=>e.open),false);
    await page.locator('#deck-stage').hover();await page.mouse.wheel(100,0);
    assert.equal(await page.locator('#deck-current').innerText(),'06');
    await page.locator('.archive-tools summary').click();
    await page.locator('[data-filter="People"]').click();
    assert.equal(await page.locator('#deck-total').innerText(),'03');
    await page.locator('#photo-search').fill('unfindable-frame');
    assert.equal(await page.locator('#deck-open').isDisabled(),true);
    assert.equal(await page.locator('#deck-empty').isVisible(),true);
    await page.locator('#photo-search').fill('');
    await page.locator('[data-filter="All"]').click();
    await page.locator('[data-layout="grid"]').click();
    assert.equal(await page.locator('.photo-card:visible').count(),12);
    await page.locator('#load-more').click();assert.equal(await page.locator('.photo-card:visible').count(),24);
    await page.locator('[data-layout="stack"]').click();
    for(const width of [320,390,768,1440]){
      await page.setViewportSize({width,height:1000});
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${width}`);
      await page.locator('#deck-next').click();
      const active=await page.locator('.deck-card[aria-pressed="true"]').boundingBox();
      assert.ok(active.x>=0 && active.x+active.width<=width,`active card fits ${width}`);
    }
    await page.setViewportSize({width:390,height:1000});
    await page.locator('#deck-stage').evaluate(e=>e.scrollIntoView({block:'center'}));
    await page.screenshot({path:'tests/archive-mobile.png'});
    await page.locator('.memory-print').first().click();assert.equal(await page.locator('#photo-dialog').evaluate(e=>e.open),true);await page.keyboard.press('Escape');
    // A physical touch gesture follows the same path as a mouse drag.
    const mobile = await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});
    const touchPage = await mobile.newPage();
    await touchPage.goto(process.env.SITE_URL || 'http://localhost:4173');
    await touchPage.locator('.deck-card[aria-pressed="true"]').waitFor();
    await touchPage.locator('#deck-stage').evaluate(e=>e.scrollIntoView({block:'center'}));
    const touchBox = await touchPage.locator('#deck-stage').boundingBox();
    const client = await mobile.newCDPSession(touchPage);
    const x=touchBox.x+touchBox.width*.7, y=touchBox.y+touchBox.height*.5;
    await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});
    for(let step=1;step<=10;step++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-step*14,y}]});
    await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    await touchPage.waitForFunction(()=>document.querySelector('#deck-current').textContent==='05');
    assert.equal(await touchPage.locator('#photo-dialog').evaluate(e=>e.open),false);
    await mobile.close();
    assert.deepEqual(errors,[]);
    console.log('PASS: journal, shelf, drag, horizontal wheel, arrow keys, wraparound, range slider, viewer/focus, filters, empty state, wall pagination, four responsive widths, memory prints, and no browser errors.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
