const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({headless: true, ...(process.env.CHROMIUM_PATH ? {executablePath: process.env.CHROMIUM_PATH} : {})});
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if(r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
  const base = process.env.SITE_URL || 'http://localhost:4173';
  await page.goto(base);
  await page.locator('[data-layout="grid"]').click();
  await page.locator('.photo-card').first().waitFor();
  assert.equal(await page.locator('.photo-card').count(), 12);
  await page.locator('#load-more').click();
  assert.equal(await page.locator('.photo-card').count(),24);
  await page.locator('#load-more').click();
  assert.equal(await page.locator('.photo-card').count(),27);
  assert.equal(await page.locator('#load-more').isVisible(),false);
  assert.equal(await page.locator('.photo-view img').evaluateAll(es=>new Set(es.map(e=>e.src)).size),27);
  for (const width of [320,375,390,768,1024,1440]) {
    await page.setViewportSize({width,height:1000});
    await page.evaluate(async () => { for(const image of document.images){image.loading='eager';} await Promise.all([...document.images].map(i => i.decode().catch(() => {}))); });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true, `Overflow at ${width}`);
    assert.deepEqual(await page.evaluate(() => [...document.images].filter(i => i.getAttribute('src') && (!i.complete || !i.naturalWidth)).map(i=>i.src)),[], `Broken images at ${width}`);
  }
  assert.deepEqual(await page.evaluate(() => [...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.getElementById(a.hash.slice(1))).map(a=>a.hash)),[]);
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'tests/desktop.png',fullPage:true});
  await page.locator('[data-filter="Coast"]').click();
  assert.equal(await page.locator('.photo-card').count(),8);
  await page.locator('[data-filter="All"]').click();
  await page.locator('#photo-search').fill('beach');
  assert.equal(await page.locator('.photo-card').count(),8);
  await page.locator('#photo-search').fill('not-a-real-photo');
  assert.equal(await page.locator('.photo-card').count(),0);
  assert.match(await page.locator('#gallery-status').innerText(),/No photographs match/);
  await page.locator('#photo-search').fill('');
  await page.locator('.save-photo').first().click();
  assert.equal(await page.locator('#saved-count').innerText(),'1');
  await page.reload();
  assert.equal(await page.locator('#saved-count').innerText(),'1');
  await page.locator('#saved-filter').click();
  assert.equal(await page.locator('.photo-card').count(),1);
  await page.locator('.save-photo').click();
  assert.equal(await page.locator('.photo-card').count(),0);
  await page.locator('#saved-filter').click();
  await page.locator('.photo-view').first().click();
  assert.equal(await page.locator('#photo-dialog').evaluate(e=>e.open),true);
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#photo-caption').innerText(),'Together by the ocean');
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('#photo-caption').innerText(),'Nature’s great masterpiece');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#photo-dialog').evaluate(e=>e.open),false);
  assert.equal(await page.locator('.photo-view').first().evaluate(e=>e===document.activeElement),true);
  await page.locator('.feature-card .card-btn').first().click();
  assert.equal(await page.locator('#photo-dialog').evaluate(e=>e.open),true);
  assert.equal(await page.locator('.dialog-controls').isVisible(),false);
  await page.locator('.dialog-close').click();
  await page.setViewportSize({width:390,height:844});
  await page.locator('.nav-open-btn').click();
  assert.equal(await page.locator('.nav-open-btn').getAttribute('aria-expanded'),'true');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.nav-open-btn').getAttribute('aria-expanded'),'false');
  await page.locator('.nav-open-btn').click();
  await page.locator('#mobile-lens-options a[href="#gallery"]').click();
  assert.equal(await page.locator('.nav-open-btn').getAttribute('aria-expanded'),'false');
  await page.locator('.photo-view').first().click();
  assert.equal(await page.locator('#photo-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
  await page.keyboard.press('Escape');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'tests/mobile.png',fullPage:true});
  // Exercise the new cinematic hero and the reference-inspired focus dial.
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#scene-next').click();
  assert.equal(await page.locator('#scene-title').innerText(),'02 — Drawn to the sea');
  assert.equal(await page.locator('[data-scene="1"]').getAttribute('aria-pressed'),'true');
  await page.locator('#scene-prev').click();
  assert.equal(await page.locator('#scene-title').innerText(),'01 — A world of green');
  await page.locator('#scene-prev').click();
  assert.equal(await page.locator('#scene-title').innerText(),'03 — Together by the ocean');
  await page.locator('[data-scene="0"]').click();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('[data-scene="1"]').evaluate(e=>e===document.activeElement),true);
  assert.equal(await page.locator('#scene-image').evaluate(e=>e.getAnimations().length),0);
  for (const target of ['gallery','featured','about','contact','home']) {
    await page.locator(`.focus-dial a[href="#${target}"]`).focus();
    await page.locator(`.focus-dial a[href="#${target}"]`).click();
    await page.waitForFunction(id=>document.querySelector('.focus-dial a[aria-current]')?.hash===`#${id}`,target);
  }
  await page.locator('.focus-dial a[href="#home"]').focus();
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.locator('.focus-dial a[href="#gallery"]').evaluate(e=>e===document.activeElement),true);
  await page.keyboard.press('End');
  assert.equal(await page.locator('.focus-dial a[href="#contact"]').evaluate(e=>e===document.activeElement),true);
  await page.locator('[data-scene="0"]').click();
  await page.evaluate(()=>document.activeElement.blur());
  await page.screenshot({path:'tests/hero-desktop.png'});
  await page.setViewportSize({width:320,height:568});
  assert.equal(await page.locator('.scene-selector').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth}),true);
  await page.locator('#scene-next').click();
  assert.equal(await page.locator('#scene-title').innerText(),'02 — Drawn to the sea');
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.locator('.nav-open-btn').click();
  await page.screenshot({path:'tests/menu-mobile.png'});
  await page.keyboard.press('Escape');
  // The wheel moves with document scrolling and snaps its active label centrally.
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.waitForFunction(()=>document.querySelector('.focus-dial a[aria-current]')?.hash==='#home');
  const startTransform = await page.locator('.dial-track').evaluate(e=>getComputedStyle(e).transform);
  await page.evaluate(()=>window.scrollTo(0,document.querySelector('#gallery').offsetTop-100));
  await page.waitForFunction(()=>document.querySelector('.focus-dial a[aria-current]')?.hash==='#gallery');
  assert.notEqual(await page.locator('.dial-track').evaluate(e=>getComputedStyle(e).transform),startTransform);
  await page.waitForTimeout(200);
  const centered = await page.locator('.dial-window').evaluate(e=>{
    const frame=e.getBoundingClientRect();const item=e.querySelector('[aria-current]').getBoundingClientRect();
    return Math.abs((frame.top+frame.bottom)/2-(item.top+item.bottom)/2)<4;
  });
  assert.equal(centered,true,'Active dial item centers on the marker');
  await page.locator('.focus-dial').hover();
  await page.mouse.wheel(0,120);
  await page.waitForFunction(()=>document.querySelector('.focus-dial a[aria-current]')?.hash==='#featured');
  await page.screenshot({path:'tests/dial-scrolled.png'});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.locator('#quiet-toggle').click();
  assert.equal(await page.locator('#quiet-toggle').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('.hero-heading').evaluate(e=>e.inert),true);
  await page.locator('#scene-next').click();
  assert.equal(await page.locator('.cinematic-hero').evaluate(e=>e.classList.contains('quiet-view')),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#quiet-toggle').getAttribute('aria-pressed'),'false');
  assert.equal(await page.locator('.hero-heading').evaluate(e=>e.inert),false);
  await page.locator('#surprise-photo').click();
  const discovery = await page.locator('#photo-caption').innerText();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#surprise-photo').evaluate(e=>e===document.activeElement),true);
  await page.locator('#surprise-photo').click();
  assert.notEqual(await page.locator('#photo-caption').innerText(),discovery);
  await page.keyboard.press('Escape');
  // Verify actual continuous movement with ordinary motion enabled.
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.waitForTimeout(650);
  await page.evaluate(()=>window.scrollTo({top:document.querySelector('#gallery').offsetTop/3,behavior:'instant'}));
  await page.waitForTimeout(40);
  const position = await page.locator('.dial-track').evaluate(e=>Number(e.style.getPropertyValue('--dial-position')));
  assert.ok(position>0 && position<1,'Dial rolls between section positions');
  await page.waitForTimeout(650);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#quiet-toggle').click();
  assert.equal(await page.locator('#quiet-toggle').getAttribute('aria-pressed'),'true');
  await page.locator('#quiet-toggle').click();
  // Large collection browsing keeps filtering and viewer selection consistent.
  await page.locator('[data-filter="People"]').click();
  assert.equal(await page.locator('.photo-card').count(),3);
  await page.locator('[data-filter="All"]').click();
  await page.locator('.photo-view').first().click();
  assert.equal(await page.locator('.filmstrip-thumb').count(),27);
  await page.locator('.filmstrip-thumb').nth(20).click();
  assert.match(await page.locator('#photo-position').innerText(),/21 \/ 27/);
  await page.locator('#dialog-image').evaluate(i=>i.decode());
  assert.equal(await page.locator('#dialog-image').evaluate(i=>i.clientWidth<=i.naturalWidth),true);
  await page.locator('#photo-next').click();
  assert.match(await page.locator('#photo-position').innerText(),/22 \/ 27/);
  await page.keyboard.press('Escape');
  await page.locator('[data-filter="Coast"]').click();
  await page.locator('.photo-view').first().click();
  assert.equal(await page.locator('.filmstrip-thumb').count(),8);
  await page.keyboard.press('Escape');
  await page.locator('[data-filter="All"]').click();
  await page.locator('#photo-search').fill('unfindable-frame');
  await page.locator('.gallery-reset').click();
  assert.equal(await page.locator('.photo-card').count(),12);
  await page.locator('[data-layout="grid"]').click();
  assert.equal(await page.locator('#photo-grid').isVisible(),true);
  // Expanded desktop navigation and new layout/motion controls.
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await page.locator('.nav-open-btn').click();
  await page.waitForTimeout(850);
  assert.equal(await page.locator('.focus-dial').evaluate(e=>e.getBoundingClientRect().width>300),true);
  for (const link of await page.locator('.focus-dial a').all()) assert.equal(await link.isVisible(),true);
  await page.screenshot({path:'tests/menu-desktop.png'});
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.nav-open-btn').getAttribute('aria-expanded'),'false');
  await page.locator('[data-layout="grid"]').click();
  assert.equal(await page.locator('#photo-grid').isVisible(),true);
  await page.locator('[data-layout="shelf"]').click();
  assert.equal(await page.locator('#archive-deck').getAttribute('data-mode'),'shelf');
  await page.locator('#motion-toggle').click();
  assert.equal(await page.locator('#motion-toggle').getAttribute('aria-pressed'),'true');
  await page.reload();
  assert.equal(await page.locator('#motion-toggle').getAttribute('aria-pressed'),'true');
  await page.locator('#scene-next').click();
  assert.equal(await page.locator('#scene-image').evaluate(e=>e.getAnimations().length),0);
  await page.locator('#motion-toggle').click();
  await page.locator('#scene-next').click();
  assert.equal(await page.locator('#scene-image').evaluate(e=>e.getAnimations().length>0),true);
  await page.locator('#motion-toggle').click();
  assert.equal(await page.locator('#scene-image').evaluate(e=>e.getAnimations().length),0);
  await page.setViewportSize({width:390,height:844});
  await page.locator('.nav-open-btn').click();
  assert.equal(await page.locator('.lens-options').evaluate(e=>getComputedStyle(e).visibility),'visible');
  await page.locator('#mobile-lens-options a[href="#featured"]').click();
  assert.equal(await page.locator('.nav-open-btn').getAttribute('aria-expanded'),'false');
  await page.locator('#motion-toggle').click();
  const noStorage = await browser.newContext();
  await noStorage.addInitScript(() => { Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage disabled');}}); });
  const restricted = await noStorage.newPage();
  await restricted.goto(base);
  await restricted.locator('[data-layout="grid"]').click();
  await restricted.locator('.save-photo').first().click();
  assert.match(await restricted.locator('#gallery-status').innerText(),/storage is unavailable/);
  assert.equal(await restricted.locator('#saved-count').innerText(),'1');
  await noStorage.close();
  const noJS = await browser.newContext({javaScriptEnabled:false});
  const staticPage = await noJS.newPage();
  await staticPage.goto(base);
  assert.equal(await staticPage.locator('.feature-card img').count(),2);
  assert.equal(await staticPage.locator('#contact .btn').isVisible(),true);
  await staticPage.setViewportSize({width:390,height:844});
  assert.equal(await staticPage.locator('nav a').first().isVisible(),true);
  assert.equal(await staticPage.locator('.nav-open-btn').isVisible(),false);
  await noJS.close();
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: six responsive widths, image and anchor integrity, filters, search, empty state, persistent favorites, restricted storage, gallery and story lightboxes, keyboard navigation, focus restoration, mobile navigation, reduced motion, no-JS content, hero scene selection and wraparound, dial section tracking and keyboard controls; no browser errors or HTTP failures.');
})().catch(e=>{console.error(e);process.exit(1)});

