const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'no-preference'}), errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.SITE_URL||'http://localhost:4173')+'/travel.html');
 await page.locator('#story-munnar summary').click();
 await page.waitForFunction(()=>document.querySelector('#story-munnar .journey-story-body').getAnimations().length>0);
 await page.locator('.journey-motion').click();
 assert.equal(await page.evaluate(()=>document.getAnimations().length),0);
 const first=page.locator('.journey-moments .journey-image-link').first();
 await first.click();
 assert.ok(await page.locator('.journey-viewer').evaluate(e=>e.open));
 await page.locator('.journey-viewer-image').evaluate(i=>i.decode());
 assert.match(await page.locator('.journey-viewer-image').getAttribute('src'),/\/images\/t1.png$/);
 const caption=await page.locator('#journey-viewer-caption').innerText();
 await page.keyboard.press('ArrowRight');
 assert.notEqual(await page.locator('#journey-viewer-caption').innerText(),caption);
 await page.keyboard.press('ArrowLeft');
 assert.equal(await page.locator('#journey-viewer-caption').innerText(),caption);
 await page.locator('.journey-viewer-image').evaluate(i=>i.decode());
 await page.screenshot({path:'tests/travel-viewer-mobile.png'});
 await page.keyboard.press('Escape');
 assert.ok(await first.evaluate(e=>e===document.activeElement));
 assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('journey-viewer-open')),false);
 await page.locator('#map').evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));
 await page.waitForFunction(()=>document.querySelector('.journey-nav a[href="#map"]').getAttribute('aria-current')==='location');
 const header=await page.locator('.journey-header').boundingBox(),nav=await page.locator('.journey-nav').boundingBox();
 assert.ok(nav.y>=header.y+header.height-1,'sticky navigation overlaps header');
 assert.ok(await page.locator('body').evaluate(e=>Number(e.style.getPropertyValue('--journey-progress'))>0));
 await page.screenshot({path:'tests/travel-navigation-mobile.png'});
 await page.locator('.journey-motion').click();
 await page.locator('[data-stop=varkala]').click();
 await page.waitForFunction(()=>document.querySelector('#map-varkala').getAnimations().length>0);
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.waitForFunction(()=>document.querySelector('.journey-motion').textContent==='Reduced motion');
 assert.equal(await page.evaluate(()=>document.getAnimations().length),0);
 for(const width of [375,390,414,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 assert.deepEqual(errors,[]);console.log('PASS: story/map animations, Pause motion, system reduced motion, original-photo viewer, keyboard navigation/focus restoration, sticky chapter tracking, reading progress and mobile bounds.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
